/*
 * Generated decision records TypeScript declaration. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/decision-records/src/cli-io.ts
 * Source path: tools/decision-records/src/cli-io.ts
 * Skill source directory: https://github.com/zxyycom/skills/tree/main/skills/decision-records
 * Rebuild: bun run sync:decision-records-cli
 */
export type DecisionRecordsCliIo = {
    stderr: (text: string) => void;
    stdout: (text: string) => void;
};
export declare const processDecisionRecordsCliIo: DecisionRecordsCliIo;
