/*
 * Generated decision records TypeScript declaration. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/decision-records/src/cli.ts
 * Source path: tools/decision-records/src/cli.ts
 * Skill source directory: https://github.com/zxyycom/skills/tree/main/skills/decision-records
 * Rebuild: bun run sync:decision-records-cli
 */
import { validateDecisionRecords } from "./index.mjs";
import { scanDecisionRecords } from "./scan.mjs";
export declare function runDecisionRecordsCli(argv?: readonly string[]): Promise<number>;
export { scanDecisionRecords, validateDecisionRecords };
export type { DecisionAlignment, DecisionCandidateDocument, DecisionDocument, DecisionId, DecisionIndex, DecisionIndexEntry, DecisionIndexMetadata, DecisionIndexStoredEntry, DecisionIndexState, DecisionListAlignment, DecisionListStatus, DecisionMetadata, DecisionProjection, DecisionRecord, DecisionRecordSource, DecisionRelation, DecisionRelationOverride, DecisionRelationType, DecisionScan, DecisionScanOptions, DecisionSuccessor, DecisionTags, DecisionStatus, DecisionSourceRevision, DecisionSourcePath, DecisionTag, EstablishedDecisionStatus, DecisionValidationResult } from "./types.mjs";
