/*
 * Generated decision records TypeScript declaration. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/decision-records/src/cli.ts
 * Source path: tools/decision-records/src/cli.ts
 * Skill source directory: https://github.com/zxyycom/skills/tree/main/skills/decision-records
 * Rebuild: bun run sync:decision-records-cli
 */
import { type DecisionRecordsCliIo } from "./cli-io.mjs";
import { renameDecisionRecord } from "./decision-rename.mjs";
import { validateDecisionRecords } from "./index.mjs";
import { scanDecisionRecords } from "./scan.mjs";
export type DecisionRecordsCliOptions = {
    cwd?: string;
    io?: DecisionRecordsCliIo;
};
export declare function runDecisionRecordsCli(argv?: readonly string[], options?: DecisionRecordsCliOptions): Promise<number>;
export { renameDecisionRecord, scanDecisionRecords, validateDecisionRecords };
export type { DecisionAlignment, DecisionCandidateDocument, DecisionDocument, DecisionId, DecisionIndex, DecisionIndexEntry, DecisionIndexMetadata, DecisionIndexState, DecisionListAlignment, DecisionListFacets, DecisionListMonthFacet, DecisionListStatus, DecisionListTagFacet, DecisionListTimeFacets, DecisionMetadata, DecisionProjection, DecisionRecord, DecisionRecordSource, DecisionRelation, DecisionRelationOverride, DecisionRelationType, DecisionScan, DecisionScanOptions, DecisionSuccessor, DecisionTags, DecisionStatus, DecisionSourceRevision, DecisionSourcePath, DecisionTag, EstablishedDecisionStatus, DecisionValidationResult } from "./types.mjs";
export type { DecisionRenameOptions, DecisionRenamePlan, DecisionRenameResult } from "./decision-rename.mjs";
