/*
 * Generated decision records TypeScript declaration. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/decision-records/src/decision-rename.ts
 * Source path: tools/decision-records/src/decision-rename.ts
 * Skill source directory: https://github.com/zxyycom/skills/tree/main/skills/decision-records
 * Rebuild: bun run sync:decision-records-cli
 */
import { type DecisionScanOptions } from "./types.mjs";
export type DecisionRenameOptions = DecisionScanOptions & Readonly<{
    preflight?: boolean;
    renameRecordedDecision?: boolean;
    source: string;
    target: string;
}>;
export type DecisionRenamePlan = Readonly<{
    affectedCandidateRelationCount: number;
    affectedEstablishedRelationCount: number;
    newId: string;
    newName: string;
    newSourcePath: string;
    oldId: string;
    oldName: string;
    oldSourcePath: string;
    outcome: "preflight" | "ready";
}>;
/** Public rename diagnostics stay portable with the generated SDK bundle. */
export type DecisionRenameDiagnostic = Readonly<{
    causeCategory?: "access-denied" | "busy" | "command-failed" | "not-found" | "not-repository" | "revision-unavailable" | "tool-unavailable" | "unknown";
    code: string;
    detail?: string | null;
    outcome?: "committed-cleanup-pending" | "no-change" | "partial-or-unknown" | "rolled-back";
    reason: string;
    recovery: string;
    scope?: string;
    target: string;
}>;
export type DecisionRenameFailure = Readonly<{
    diagnostics: DecisionRenameDiagnostic[];
    errors: string[];
    exitCode: 1 | 2;
    plan: null;
    presentation: "command" | "plain";
    status: "error";
}>;
export type DecisionRenameAttention = Readonly<{
    diagnostics: DecisionRenameDiagnostic[];
    exitCode: 1;
    plan: DecisionRenamePlan;
    status: "attention";
    warnings: string[];
}>;
export type DecisionRenameCommittedCleanup = Readonly<{
    changed: true;
    diagnostics: DecisionRenameDiagnostic[];
    errors: [];
    exitCode: 1;
    outcome: "committed-cleanup-pending";
    plan: DecisionRenamePlan;
    status: "attention";
    warnings: string[];
}>;
export type DecisionRenameResult = DecisionRenameFailure | DecisionRenameAttention | DecisionRenameCommittedCleanup | Readonly<{
    changed: boolean;
    diagnostics: [];
    errors: [];
    outcome: "committed" | "preflight";
    plan: DecisionRenamePlan;
    status: "ok";
}>;
/** Renames one Decision identity and every managed relation that targets it. */
export declare function renameDecisionRecord(options: DecisionRenameOptions): Promise<DecisionRenameResult>;
