/*
 * Generated decision records TypeScript declaration. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/decision-records/src/index.ts
 * Source path: tools/decision-records/src/index.ts
 * Skill source directory: https://github.com/zxyycom/skills/tree/main/skills/decision-records
 * Rebuild: bun run sync:decision-records-cli
 */
import { type DecisionId, type DecisionScan, type DecisionScanOptions, type DecisionValidationResult } from "./types.mjs";
export type DecisionValidationContext = {
    result: DecisionValidationResult;
};
export type DecisionValidationOptions = {
    allowEmptyDecisionSet?: boolean;
    checkIndexText?: boolean;
    scanErrorPolicy?: "omit" | "source-only";
};
export type EstablishedDecisionIdSelection = {
    decisionIds: DecisionId[];
    errors: string[];
};
export declare function selectEstablishedDecisionIds(scan: DecisionScan): EstablishedDecisionIdSelection;
export declare function validateDecisionRecords(options?: DecisionScanOptions): Promise<DecisionValidationResult>;
export declare function loadDecisionValidationContext(options?: DecisionScanOptions, validationOptions?: DecisionValidationOptions): Promise<DecisionValidationContext>;
export declare function validateDecisionScan(scan: DecisionScan, options?: DecisionValidationOptions): Promise<DecisionValidationResult>;
