/*
 * Generated decision records TypeScript declaration. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/decision-records/src/scan-relations.ts
 * Source path: tools/decision-records/src/scan-relations.ts
 * Skill source directory: https://github.com/zxyycom/skills/tree/main/skills/decision-records
 * Rebuild: bun run sync:decision-records-cli
 */
import type { DecisionScanLocation } from "./scan-contracts.mjs";
import type { DecisionIndex, DecisionProjection, DecisionRecord } from "./types.mjs";
export declare function unindexedDecisionError(indexRelativePath: string, decisionId: string): string;
export declare function missingIndexedDecisionError(indexRelativePath: string, decisionId: string): string;
export declare function appendMissingIndexedRecords(records: DecisionRecord[], index: DecisionIndex | null, location: DecisionScanLocation, indexErrors: string[]): void;
export declare function validateScannedRelationships(records: readonly DecisionRecord[], sourceErrors: string[]): void;
export declare function selectProjection(source: DecisionProjection): DecisionProjection;
export declare function emptyDecisionProjection(): DecisionProjection;
