/*
 * Generated decision records TypeScript declaration. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/decision-records/src/scan-contracts.ts
 * Source path: tools/decision-records/src/scan-contracts.ts
 * Skill source directory: https://github.com/zxyycom/skills/tree/main/skills/decision-records
 * Rebuild: bun run sync:decision-records-cli
 */
import type { DecisionId, DecisionIndex, DecisionRecord } from "./types.mjs";
export type DecisionStoredIndexEntry = DecisionIndex["entries"][DecisionId];
export type SourceFile = {
    decisionPath: string;
    sourcePath: string;
    sourceText?: string;
};
export type SourceFileMembers = [SourceFile, ...SourceFile[]];
export type DecisionScanLocation = {
    decisionsDirectory: string;
    decisionsLabel: string;
    indexPath: string;
    indexRelativePath: string;
    workspaceRoot: string;
};
export type ScannedSourceState = Pick<DecisionRecord, "activationCandidate" | "bodyReady" | "document" | "scaffoldValid" | "source">;
export type CandidateSourceState = Pick<ScannedSourceState, "activationCandidate" | "bodyReady" | "scaffoldValid">;
export type ScannedSourceMetadata = Pick<DecisionRecord, "alignment" | "createdAt" | "projection" | "status" | "tags">;
