/*
 * Generated decision records TypeScript declaration. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/decision-records/src/scan.ts
 * Source path: tools/decision-records/src/scan.ts
 * Skill source directory: https://github.com/zxyycom/skills/tree/main/skills/decision-records
 * Rebuild: bun run sync:decision-records-cli
 */
import { type DecisionScan, type DecisionScanOptions } from "./types.mjs";
export declare function unindexedDecisionError(indexRelativePath: string, decisionId: string): string;
export declare function decisionIndexRequiredError(indexRelativePath: string): string;
export declare function missingIndexedDecisionError(indexRelativePath: string, decisionId: string): string;
export declare function scanDecisionRecords(options?: DecisionScanOptions): Promise<DecisionScan>;
