/*
 * Generated decision records TypeScript declaration. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/decision-records/src/types.ts
 * Source path: tools/decision-records/src/types.ts
 * Skill source directory: https://github.com/zxyycom/skills/tree/main/skills/decision-records
 * Rebuild: bun run sync:decision-records-cli
 */
export declare const decisionRelationTypes: readonly ["修订", "替代", "判定无效", "归并", "拆分", "重划"];
export type DecisionRelationType = (typeof decisionRelationTypes)[number];
export type DecisionTraceDirection = "both" | "predecessors" | "successors";
export declare const decisionStatuses: readonly ["candidate", "active", "archived"];
export type DecisionStatus = (typeof decisionStatuses)[number];
export declare const establishedDecisionStatuses: readonly ["active", "archived"];
export type EstablishedDecisionStatus = (typeof establishedDecisionStatuses)[number];
export type DecisionListStatus = EstablishedDecisionStatus | "all";
export declare const decisionAlignments: readonly ["aligned", "unaligned"];
export type DecisionAlignment = (typeof decisionAlignments)[number];
export type DecisionListAlignment = DecisionAlignment | "all";
declare const decisionIdBrand: unique symbol;
declare const decisionSourcePathBrand: unique symbol;
declare const decisionTagBrand: unique symbol;
/** A validated stable extensionless identity such as `use-stable-ids`. */
export type DecisionId = string & {
    readonly [decisionIdBrand]: "DecisionId";
};
/** A validated root or archive path for one decision Markdown source. */
export type DecisionSourcePath = string & {
    readonly [decisionSourcePathBrand]: "DecisionSourcePath";
};
/** A validated kebab-case decision tag. */
export type DecisionTag = string & {
    readonly [decisionTagBrand]: "DecisionTag";
};
export type DecisionRelation = {
    type: DecisionRelationType;
    target: DecisionId;
    summary?: string;
};
/** A CLI relation-summary input before its target selector is resolved. */
export type DecisionRelationSummary = {
    target: DecisionId;
    summary?: string;
};
export type DecisionSuccessor = {
    alignment: DecisionAlignment;
    decisionId: DecisionId;
};
export type DecisionRelationOverride = {
    kind: "source";
} | {
    kind: "replace";
    relations: DecisionRelation[];
    relationSummaries?: DecisionRelationSummary[];
};
export type DecisionProjection = {
    title: string;
    purpose: string;
    background: string;
    decision: string;
    relations: DecisionRelation[];
};
export type DecisionTags = {
    tags: DecisionTag[];
};
export type DecisionMetadata = {
    status: "active";
    alignment: "aligned";
    createdAt: string;
} | {
    status: "active";
    alignment: "unaligned";
    createdAt: string;
} | {
    status: "archived";
    alignment: DecisionAlignment | null;
    createdAt: string;
};
export type DecisionDocument = DecisionProjection & DecisionTags & DecisionMetadata;
export type DecisionCandidateDocument = DecisionProjection & DecisionTags & {
    status: "candidate";
    alignment: null;
    createdAt: null;
};
export type DecisionRecordSource = {
    body: string;
    document: DecisionCandidateDocument;
    kind: "candidate";
    text: string;
} | {
    body: string;
    document: DecisionDocument;
    kind: "established";
    text: string;
} | {
    kind: "invalid";
    text: string;
} | {
    kind: "missing";
};
export type DecisionIndexState = Omit<DecisionDocument, "alignment"> & {
    /** Absent for archived records so the optional query field has no value. */
    alignment?: DecisionAlignment;
    name: string;
    sourcePath: DecisionSourcePath;
};
export type DecisionSource = Readonly<{
    decisionId: DecisionId;
    sourcePath: DecisionSourcePath;
    text: string;
}>;
/** Raw in-memory source input that must be validated before domain use. */
export type DecisionSourceInput = Readonly<{
    decisionId: string;
    sourcePath: string;
    text: string;
}>;
export type DecisionIndexEntry = {
    id: DecisionId;
    state: DecisionIndexState;
};
export type DecisionIndexMetadata = Record<string, never>;
export type DecisionSourceRevision = {
    metadata: string;
    entries: Record<DecisionId, string>;
};
export type DecisionIndex = {
    schemaVersion: 4;
    namespace: "decisions";
    definitionVersion: 10;
    metadata: DecisionIndexMetadata;
    sourceRevision: DecisionSourceRevision;
    entries: Record<DecisionId, DecisionIndexState>;
};
export type DecisionRecord = {
    /** Whether the source is a body-ready candidate eligible for activation. */
    activationCandidate: boolean;
    /** Whether this source has a valid candidate scaffold shape. */
    scaffoldValid: boolean;
    /** Whether the fixed candidate body passes mechanical readiness checks. */
    bodyReady: boolean;
    alignment: DecisionAlignment | null;
    createdAt: string | null;
    /** Raw basename for invalid sources; validated on candidate/established records. */
    decisionId: string;
    decisionPath: string;
    document: DecisionDocument | null;
    markdownExists: boolean;
    projection: DecisionProjection;
    relationshipErrors: string[];
    source: DecisionRecordSource;
    sourcePath: string;
    status: DecisionStatus | null;
    tags: DecisionTag[];
};
type DecisionRecordWithSource<Kind extends DecisionRecordSource["kind"]> = Omit<DecisionRecord, "source"> & {
    decisionId: DecisionId;
    sourcePath: DecisionSourcePath;
    source: Extract<DecisionRecordSource, {
        kind: Kind;
    }>;
};
export type DecisionCandidateRecord = DecisionRecordWithSource<"candidate">;
export type EstablishedDecisionRecord = DecisionRecordWithSource<"established">;
export declare function isActivationCandidateRecord(record: DecisionRecord): record is DecisionCandidateRecord;
export declare function isDecisionCandidateRecord(record: DecisionRecord): record is DecisionCandidateRecord;
export declare function isEstablishedDecisionRecord(record: DecisionRecord): record is EstablishedDecisionRecord;
export declare function compareDecisionRecords(left: Pick<DecisionRecord, "sourcePath">, right: Pick<DecisionRecord, "sourcePath">): number;
export type DecisionScanOptions = {
    decisionsDir?: string;
    workspaceRoot?: string;
};
export type DecisionScan = {
    /** Source collection errors that prevent returning a partial candidate query. */
    collectionErrors: string[];
    decisionsDirectoryAvailable: boolean;
    decisionsDirectory: string;
    errors: string[];
    indexErrors: string[];
    index: DecisionIndex | null;
    indexExists: boolean;
    indexPath: string;
    indexRelativePath: string;
    indexText: string;
    records: DecisionRecord[];
    sourceErrors: string[];
    workspaceRoot: string;
};
export type DecisionValidationResult = {
    /** Compatibility count of body-ready candidates eligible for activation. */
    activationCandidateCount: number;
    /** Number of mechanically body-ready candidate scaffolds. */
    bodyReadyCandidateCount: number;
    activeCount: number;
    alignedCount: number;
    archivedCount: number;
    decisionCount: number;
    errors: string[];
    scan: DecisionScan;
    /** Number of structurally valid candidate scaffolds. */
    scaffoldCandidateCount: number;
    unalignedCount: number;
};
export type MarkdownSection = {
    content: string;
    heading: string;
    index: number;
};
export {};
