/*
 * Generated investigation report checker TypeScript declarations. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/investigation-report/api/check-investigations.d.mts
 * Source path: tools/investigation-report/api/check-investigations.d.mts
 * Skill source directory: https://github.com/zxyycom/skills/tree/main/skills/investigation-report
 * Rebuild: bun run sync:investigation-report-check
 */
export type InvestigationRelationType =
  | "补充"
  | "复查"
  | "修正"
  | "推翻"
  | "归并"
  | "拆分";

export type InvestigationRelation = {
  type: InvestigationRelationType;
  target: string;
  summary?: string;
};

export type InvestigationCandidateReadiness = {
  bodyReady: boolean;
  resourceReady: boolean;
  scaffoldValid: boolean;
};

export type InvestigationCandidate = {
  errors: string[];
  id: string;
  markdown: string | null;
  path: string;
  readiness: InvestigationCandidateReadiness;
  warnings: string[];
};

export type InvestigationCandidateCreateOptions = {
  formedAt: string;
  id: string;
  investigationsDir?: string;
  question: string;
  relations: readonly InvestigationRelation[];
  tags: readonly string[];
  title: string;
  workspaceRoot: string;
};

export type InvestigationCandidateCreateResult = {
  candidate: InvestigationCandidate | null;
  changed: boolean;
  errors: string[];
  status: "ok" | "invalid-options" | "error";
  warnings: string[];
};

export type InvestigationCandidateListOptions = {
  investigationsDir?: string;
  workspaceRoot: string;
};

export type InvestigationCandidateListResult = {
  candidates: InvestigationCandidate[];
  errors: string[];
  status: "ok" | "error";
  warnings: string[];
};

export type InvestigationCandidateShowOptions = {
  id: string;
  investigationsDir?: string;
  workspaceRoot: string;
};

export type InvestigationCandidateShowResult = {
  candidate: InvestigationCandidate | null;
  errors: string[];
  status: "ok" | "error";
  warnings: string[];
};

export type InvestigationCandidatePublishOptions = {
  ids: readonly string[];
  investigationsDir?: string;
  preflight?: boolean;
  workspaceRoot: string;
};

export type InvestigationCandidatePublishResult = {
  changed: boolean;
  errors: string[];
  ids: string[];
  indexPath: string;
  preflight: boolean;
  warnings: string[];
};

export type InvestigationCandidateDiscardOptions = {
  deleteOwnedResources?: boolean;
  deleteRecordedCandidate?: boolean;
  id: string;
  investigationsDir?: string;
  workspaceRoot: string;
};

export type InvestigationCandidateDiscardResult = {
  changed: boolean;
  deletedResourceIds: string[];
  errors: string[];
  id: string;
  requiresRecordedDeletionConfirmation: boolean;
};

export type InvestigationRenameOptions = {
  investigationsDir?: string;
  preflight?: boolean;
  renameRecordedCandidate?: boolean;
  renameRecordedReport?: boolean;
  source: string;
  target: string;
  workspaceRoot: string;
};

export type InvestigationRenamePlan = {
  affectedCandidateRelationCount: number;
  affectedEstablishedRelationCount: number;
  affectedResourceReferenceCount: number;
  newId: string;
  newName: string;
  newSourcePath: string;
  oldId: string;
  oldName: string;
  oldSourcePath: string;
  outcome: "preflight" | "ready";
  resourceOwnerMoved: boolean;
};

export type InvestigationRenameResult = {
  changed: boolean;
  errors: string[];
  indexPath: string;
  plan: InvestigationRenamePlan | null;
  status: "attention" | "error" | "ok";
};

export type InvestigationReportCheckOptions = {
  ids?: readonly string[];
  investigationsDir?: string;
  workspaceRoot: string;
};

export type InvestigationReportCheckResult = {
  availableReportCount: number;
  errors: string[];
  indexChecked: boolean;
  indexPath: string;
  selectedReportCount: number;
  warnings: string[];
};

export type InvestigationIndexSyncOptions = {
  investigationsDir?: string;
  mode?: "check" | "write";
  selectors?: readonly string[];
  workspaceRoot: string;
};

export type InvestigationIndexSyncResult = {
  changed: boolean;
  changedIds: string[];
  diagnostics: Array<{
    code: string;
    reason: string;
    recovery: string;
    target: string;
  }>;
  errors: string[];
  indexPath: string;
  reportCount: number;
  scope: "all" | "selected";
  selectedIds: string[];
  state: string;
  warnings: string[];
};

export type InvestigationIndexStageOptions = {
  investigationsDir?: string;
  reportIds: readonly string[];
  workspaceRoot: string;
};

export type InvestigationIndexStageDiagnostic = {
  code: string;
  message: string;
  path: string | null;
  stateId: string | null;
};

type InvestigationIndexStageBase = {
  diagnostics: InvestigationIndexStageDiagnostic[];
  indexPath: string;
  namespace: string;
  selectedIds: string[];
};

export type InvestigationIndexStageResult =
  | (InvestigationIndexStageBase & {
      changed: true;
      state: "staged";
      status: "ok";
    })
  | (InvestigationIndexStageBase & {
      changed: false;
      state: "unchanged";
      status: "ok";
    })
  | (InvestigationIndexStageBase & {
      changed: false;
      state: string;
      status: "error";
    })
  | (InvestigationIndexStageBase & {
      changed: null;
      state: "pending-recovery-failed";
      status: "error";
    });

export type InvestigationIndexState = {
  formedAt: string;
  question: string;
  relations: InvestigationRelation[];
  resourceIds: string[];
  tags: string[];
  title: string;
};

export type InvestigationIndexQueryOptions = {
  direction?: "predecessors" | "successors" | "both";
  formedAtFrom?: string;
  formedAtTo?: string;
  investigationsDir?: string;
  limit?: number;
  offset?: number;
  relatedTo?: string;
  relationType?: InvestigationRelationType;
  tags?: readonly string[];
  text?: string;
  workspaceRoot: string;
};

export type InvestigationIndexQueryResult = {
  entries: Array<{ id: string; state: InvestigationIndexState }>;
  errors: string[];
  indexPath: string;
  limit: number;
  offset: number;
  total: number;
};

export type InvestigationRelationReplacement = {
  relations: readonly InvestigationRelation[];
  source: string;
};

export type InvestigationRelationSetOptions = {
  investigationsDir?: string;
  replacements: readonly InvestigationRelationReplacement[];
  workspaceRoot: string;
};

export type InvestigationRelationSetResult = {
  changed: boolean;
  errors: string[];
  indexPath: string;
  sourceIds: string[];
};

export type InvestigationReportShowOptions = {
  id: string;
  investigationsDir?: string;
  workspaceRoot: string;
};

export type InvestigationReportShowResult = {
  errors: string[];
  id: string;
  indexPath: string;
  markdown: string | null;
  state: InvestigationIndexState | null;
  status: "ok" | "error";
};

export type InvestigationReportTraceOptions = {
  direction?: "predecessors" | "successors" | "both";
  id: string;
  investigationsDir?: string;
  maxDepth?: number;
  workspaceRoot: string;
};

export type InvestigationReportTraceResult = {
  edges: Array<{
    source: string;
    target: string;
    type: InvestigationRelationType;
    summary?: string;
  }>;
  errors: string[];
  id: string;
  indexPath: string;
  reportIds: string[];
  status: "ok" | "error";
};

export declare function runInvestigationReportCheckCli(
  argv?: readonly string[]
): Promise<number>;
export declare function synchronizeInvestigationIndex(
  options: InvestigationIndexSyncOptions
): Promise<InvestigationIndexSyncResult>;
export declare function stageInvestigationIndex(
  options: InvestigationIndexStageOptions
): Promise<InvestigationIndexStageResult>;
export declare function queryInvestigationIndex(
  options: InvestigationIndexQueryOptions
): Promise<InvestigationIndexQueryResult>;
export declare function showInvestigationReport(
  input: unknown
): Promise<InvestigationReportShowResult>;
export declare function traceInvestigationReports(
  input: unknown
): Promise<InvestigationReportTraceResult>;
export declare function setInvestigationRelations(
  input: unknown
): Promise<InvestigationRelationSetResult>;
export declare function validateInvestigationReports(
  options: InvestigationReportCheckOptions
): Promise<InvestigationReportCheckResult>;

export type InvestigationReportDiscardOptions = {
  deleteOwnedResources?: boolean;
  deleteRecordedReport?: boolean;
  id: string;
  investigationsDir?: string;
  workspaceRoot: string;
};

export type InvestigationReportDiscardResult = {
  changed: boolean;
  deletedResourceIds: string[];
  errors: string[];
  id: string;
  indexPath: string;
  requiresRecordedDeletionConfirmation: boolean;
};

export declare function discardInvestigationReport(
  input: unknown
): Promise<InvestigationReportDiscardResult>;

export declare function createInvestigationCandidate(
  input: unknown
): Promise<InvestigationCandidateCreateResult>;
export declare function listInvestigationCandidates(
  input: unknown
): Promise<InvestigationCandidateListResult>;
export declare function showInvestigationCandidate(
  input: unknown
): Promise<InvestigationCandidateShowResult>;
export declare function publishInvestigationCandidates(
  input: unknown
): Promise<InvestigationCandidatePublishResult>;
export declare function discardInvestigationCandidate(
  input: unknown
): Promise<InvestigationCandidateDiscardResult>;
export declare function renameInvestigationRecord(
  options: InvestigationRenameOptions
): Promise<InvestigationRenameResult>;

export type InvestigationSearchOptions = {
  direction?: "predecessors" | "successors" | "both";
  formedAtFrom?: string;
  formedAtTo?: string;
  in?: "content" | "metadata";
  investigationsDir?: string;
  limit?: number;
  match?: "all" | "any" | "phrase";
  query: string;
  relatedTo?: string;
  relationType?: InvestigationRelationType;
  tags?: readonly string[];
  workspaceRoot: string;
};
export type InvestigationContentSearchEntry = {
  formedAt: string;
  id: string;
  previews: ReadonlyArray<{
    column: number | null;
    line: number;
    preview: string;
  }>;
  question: string;
  sourcePath: string;
  tags: readonly string[];
  title: string;
};
export type InvestigationMetadataSearchField =
  | "id"
  | "name"
  | "title"
  | "question"
  | "tags";
export type InvestigationMetadataMatchedRelation = {
  summary: string;
  target: string;
  type: InvestigationRelationType;
};
export type InvestigationMetadataSearchEntry = {
  formedAt: string;
  id: string;
  matchedFields: readonly InvestigationMetadataSearchField[];
  matchedRelations: readonly InvestigationMetadataMatchedRelation[];
  question: string;
  sourcePath: string;
  tags: readonly string[];
  title: string;
};
export type InvestigationSearchEntry =
  | InvestigationContentSearchEntry
  | InvestigationMetadataSearchEntry;
export type InvestigationSearchResult = {
  entries: readonly InvestigationSearchEntry[];
  errors: readonly string[];
  indexPath: string;
  status: "error" | "ok";
  warnings: readonly string[];
};
export declare function searchInvestigationReports(
  input: unknown
): Promise<InvestigationSearchResult>;
