/*
 * Generated decision-records TypeScript declarations. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/decision-records/api/decision-records.d.mts
 * Source path: tools/decision-records/api/decision-records.d.mts
 * Skill source directory: https://github.com/zxyycom/skills/tree/main/skills/decision-records
 * Rebuild: bun run sync:decision-records-cli
 */
export type DecisionRelationType =
  | "修订"
  | "替代"
  | "判定无效"
  | "归并"
  | "拆分";

export type DecisionStatus = "candidate" | "active" | "archived";

export type EstablishedDecisionStatus = "active" | "archived";

export type DecisionListStatus = EstablishedDecisionStatus | "all";

export type DecisionAlignment = "aligned" | "unaligned";

export type DecisionListAlignment = DecisionAlignment | "all";

export type DecisionRelation = {
  type: DecisionRelationType;
  target: string;
};

export type DecisionSuccessor = {
  alignment: DecisionAlignment;
  recordPath: string;
};

export type DecisionRelationOverride =
  | { kind: "source" }
  | {
      kind: "replace";
      relations: DecisionRelation[];
    };

export type DecisionDomainDefinition = {
  id: string;
  description: string;
};

export type DecisionProjection = {
  title: string;
  purpose: string;
  background: string;
  decision: string;
  relations: DecisionRelation[];
};

export type DecisionMetadata =
  | {
    status: "active";
    alignment: "aligned";
    createdAt: string;
  }
  | {
    status: "active";
    alignment: "unaligned";
    createdAt: string;
  }
  | {
    status: "archived";
    alignment: DecisionAlignment | null;
    createdAt: string;
  };

export type DecisionDocument = DecisionProjection & DecisionMetadata;

export type DecisionCandidateDocument = DecisionProjection & {
  status: "candidate";
  alignment: null;
  createdAt: null;
};

export type DecisionRecordSource =
  | {
      body: string;
      document: DecisionCandidateDocument;
      kind: "candidate";
      text: string;
    }
  | {
      body: string;
      document: DecisionDocument;
      kind: "established";
      text: string;
    }
  | {
      kind: "invalid";
      text: string;
    }
  | {
      kind: "missing";
    };

export type DecisionIndexState = DecisionDocument & {
  path: string;
};

export type DecisionIndexStoredEntry = {
  keys: Record<string, Array<boolean | number | string>>;
  state: DecisionIndexState;
};

export type DecisionIndexEntry = DecisionIndexStoredEntry & {
  id: string;
};

export type DecisionIndexMetadata = {
  domains: DecisionDomainDefinition[];
};

export type DecisionSourceRevision = {
  metadata: string;
  entries: Record<string, string>;
};

export type DecisionIndex = {
  schemaVersion: 3;
  namespace: "decisions";
  definitionVersion: 5;
  metadata: DecisionIndexMetadata;
  sourceRevision: DecisionSourceRevision;
  keyDefinitions: Array<{
    name: string;
    mode: "exact" | "range" | "text";
  }>;
  entries: Record<string, DecisionIndexStoredEntry>;
};

export type DecisionRecord = {
  /** Whether the source is a complete candidate eligible for activation. */
  activationCandidate: boolean;
  alignment: DecisionAlignment | null;
  bodyValid: boolean;
  createdAt: string | null;
  decisionPath: string;
  document: DecisionDocument | null;
  domain: string;
  fileName: string;
  indexed: boolean;
  markdownExists: boolean;
  projection: DecisionProjection;
  relativePath: string;
  relationshipErrors: string[];
  source: DecisionRecordSource;
  status: DecisionStatus | null;
};

export type DecisionScanOptions = {
  decisionsDir?: string;
  workspaceRoot?: string;
};

export type DecisionScan = {
  /** @deprecated Candidates no longer produce validation errors; always empty. */
  activationCandidateErrors: string[];
  /** Source collection errors that prevent returning a partial candidate query. */
  collectionErrors: string[];
  decisionsDirectoryAvailable: boolean;
  decisionsDirectory: string;
  /** Validated domain catalog definitions from the same source scan. */
  domainDefinitions: DecisionDomainDefinition[];
  domainErrors: string[];
  domainIds: Set<string>;
  errors: string[];
  index: DecisionIndex | null;
  indexErrors: string[];
  indexExists: boolean;
  indexPath: string;
  indexRelativePath: string;
  indexText: string;
  records: DecisionRecord[];
  sourceErrors: string[];
  workspaceRoot: string;
};

export type DecisionValidationResult = {
  /** Number of complete candidates eligible for activation. */
  activationCandidateCount: number;
  activeCount: number;
  alignedCount: number;
  archivedCount: number;
  decisionCount: number;
  domainCount: number;
  errors: string[];
  scan: DecisionScan;
  unalignedCount: number;
};

export declare function runDecisionRecordsCli(
  argv?: readonly string[]
): Promise<number>;

export declare function scanDecisionRecords(
  options?: DecisionScanOptions
): Promise<DecisionScan>;

export declare function validateDecisionRecords(
  options?: DecisionScanOptions
): Promise<DecisionValidationResult>;
