/*
 * Generated decision records TypeScript declaration entry. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/decision-records/src/cli.ts
 * Source path: tools/decision-records/src/cli.ts
 * Skill source directory: https://github.com/zxyycom/skills/tree/main/skills/decision-records
 * Rebuild: bun run sync:decision-records-cli
 */
export * from "./decision-records-sdk/cli.mjs";
