/*
 * Generated skill self-updater TypeScript declarations. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/scripts/templates/update-skill.d.mts
 * Source path: scripts/templates/update-skill.d.mts
 * Skill source directory: https://github.com/zxyycom/skills/tree/main/skills/decision-records
 * Rebuild: bun run sync:skill-updaters
 */
export type UpdaterConfig = {
  packageLockAssetName: string;
  releaseAssetName: string;
  repo: string;
  skillName: string;
  sourcePath: string;
};

export declare const skillUpdaterConfig: Readonly<UpdaterConfig>;

export declare function runSkillUpdaterCli(
  argv?: readonly string[]
): Promise<number>;
