/*
 * Generated TestEvidenceStateIndex schema-derived TypeScript declarations. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/test-evidence/src/schemas.ts
 * Source path: tools/test-evidence/src/schemas.ts
 * Skill source directory: https://github.com/zxyycom/skills/tree/main/skills/test-evidence-review
 * Rebuild: bun run sync:test-evidence-cli
 */
export interface TestEvidenceStateIndex {
  definitionVersion: 3;
  entries: {
    id: string;
    keys: {
      /**
       * @minItems 1
       */
      search: [unknown, ...unknown[]];
      /**
       * @minItems 1
       */
      topic: [unknown, ...unknown[]];
    };
    state: {
      endLine: number;
      /**
       * @minItems 1
       */
      entries: [string, ...string[]];
      id: string;
      line: number;
      sourcePath: string;
      summary: string;
      title: string;
      searchText: string;
    };
  }[];
  /**
   * @minItems 2
   */
  keyDefinitions: [unknown, unknown, ...unknown[]];
  metadata: {
    /**
     * @minItems 1
     */
    topics: [
      {
        description: string;
        id: string;
      },
      ...{
        description: string;
        id: string;
      }[]
    ];
  };
  namespace: "test-evidence";
  schemaVersion: 2;
  sourceRevision: string;
}
