/*
 * Generated TestEvidenceTopicCatalog schema-derived TypeScript declarations. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/test-evidence/src/schemas.ts
 * Source path: tools/test-evidence/src/schemas.ts
 * Skill source directory: https://github.com/zxyycom/skills/tree/main/skills/test-evidence-review
 * Rebuild: bun run sync:test-evidence-cli
 */
export interface TestEvidenceTopicCatalog {
  schemaVersion: 1;
  /**
   * @minItems 1
   */
  topics: [
    {
      description: string;
      id: string;
    },
    ...{
      description: string;
      id: string;
    }[]
  ];
}
